### ISSUE TITLE
openDialog/canSelectMany: the default separator " " gets escaped i.e. "\ "

### ISSUE THREAD

**Issue by nanonano** [rioj7/command-variable#104]
For an openDialog with canSelectMany, the default separator " ", gets escaped.

For example:
`file1.csv\ file2.csv`

If you are passing this variable as "args" in launch.json, it can cause problems as multiple files are seen as a single file with the name "file1.csv file2.csv".

Is there any way around this so the filenames are separated with just a space.

**Comment by rioj7** [comment]
@nanonano The problem is how VSC constructs the full command line, how it escapes the arguments, quotes/no-quotes. I had an discussion a few years ago about how VSC handles file redirection in the command, it escapes the `<` and `>`.
They handle it differently for different shells, cmd, PS, bash. And the problem was related to handling environment variables, the maintainer of that part was stubborn that it should restore the environment to the state before the command. My argument was If I make a mess of the environment by not deleting variables I just close the shell and start a new one.

Regarding the command line VSC should have an option to let the user build the full string as if he typed it in himself and skip the "smart" handling done by VSC. And have the possibility to write a version of the line for a specific shell, Now VSC wants to handle all shells with the same launch config, maybe that will work in 99% of the cases, but there is always someone with a specific need and that is then not possible. Unfortunately there are not a lot users shouting for such a feature.

What you could do is construct 1 argument and pass it to a shell script that uses that string to construct a command and execute it.

I can't instruct VSC to handle an array result of a command as separate arguments.

You can save the result string op `OpenDialog` in the remember store and give `OpenDialog` the `empty` argument. Then use a bunch of `extension.commandvariable.transform` commands to pick field 0, 1, 2, 3, 4 from a remember variable, and return an empty string if that field is not found. To handle filenames with spaces (a very bad idea) you should use a different separator.

Have you tried to skip the `arguments` property and construct all in the `command` property of the launch config. As long as you don't use environment variables in the launch config it might work.

**Comment by nanonano** [comment]
@rioj7 thanks for the detailed explanation, it's really appreciated.

I had a feeling it would be something VSC was doing, and not your extension.

> Have you tried to skip the arguments property and construct all in the command property of the launch config. As long as you don't use environment variables in the launch config it might work.

Not sure what you mean, I don't think there is a command property for launch.json, only tasks.json? Below is from my launch.json.

```
        {   
            "name": "Python Debugger: bittytax_conv",
            "type": "debugpy",
            "request": "launch",
            "module": "bittytax.conv.bittytax_conv",
            "args": [
                "${input:pickDataFilename}",
                "--format",
                "${input:getFormat}",
                "--debug"
            ]
        },
```

**Comment by rioj7** [comment]
@nanonano  debugpy has a feature (maybe other debug launchers too) that you can supply the exact formatted arguments and thus bypass VSC "intelligent" escaping and quoting.

```json
        {   
            "name": "Python Debugger: bittytax_conv",
            "type": "debugpy",
            "request": "launch",
            "module": "bittytax.conv.bittytax_conv",
            "args": "${input:pickDataFilename} --format ${input:getFormat} --debug"
        },
```

I have tried it with a launch config for the current Python file (`program` property), and for `module` debugging.

**Comment by nanonano** [comment]
@rioj7, thanks so much for your help, that's worked a treat.

I didn't realise you could pass all the args as a single string.

I changed the separator in openDialog to a "," and then used transform to escape any spaces in the filenames, and finally to convert "," back to a normal space.

**Comment by bpayne312** [comment]
Hello, apologies to comment on a closed issue rather than starting a fresh one - but just wanted to ask a quick question please about something you said on 4th December @rioj7 

You said "I can't instruct VSC to handle an array result of a command as separate arguments" - I wonder if this is related to something I've been struggling with recently.

I used to (last known to be working on 6th December 2024) provide a list of arguments in the format "KEY1=--arg1 --arg2 --arg3" in a file, then use extension.commandvariable.file.content to read that line (using the key at the start).  The args would be split at the spaces and everything worked great.  

More recently, these are no longer split at the spaces and it's treated like one long argument with spaces in it.  I've tried rolling back this extension and VS Code to see if I can get the old behaviour back - but I've been unsuccessful.  I might've been using quite an old version of VSC possibly?

That's a lot of words - apologies.  I basically wanted to ask, did this work before?  Has VSC changed?

**Comment by rioj7** [comment]
@bpayne312 It probably works if you construct the arguments in a single string, and not using an array of strings. But it might depends on the language you use.

The extension has not changed around 2024-12-06.
v1.66.0 is from 2024-11-12
v1.67.0 is from 2025-02-26

Can you show your task/launch (with dummy strings)?

**Comment by bpayne312** [comment]
Thank you very much for your response @rioj7 

Previously (December 2024), I would have the following (this is on windows 11, using the Microsoft C/C++ extension for debugging):

A file "ConfigData" for the user to provide inputs, including the args I've been having trouble with
```
KEY0=c:/path/to/thing
KEY1=--arg1 --arg2 --arg3
```
Then in launch.json
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug Bob",
            "presentation": {
                "hidden": false,
                "group": "Default",
                "order": 1
            },
            "type": "cppvsdbg",
            "request": "launch",
            "program": "${workspaceFolder}/path/Bob.exe",
            "args": [
                "${input:GetARG}"
            ],
            "stopAtEntry": false,
            "cwd": "${input:GetCWD}",
            "environment": [],
            "externalConsole": false,
            "preLaunchTask": "${defaultBuildTask}"
        }
... (then a few more configs) ...
"inputs": [
        {
            "id": "GetARG",
            "type": "command",
            "command": "extension.commandvariable.file.content",
            "args": {
                "fileName": "${workspaceFolder}/.vscode/ConfigData",
                "key": "KEY0",
                "default": ""
            }
        },
        {
            "id": "GetCWD",
            "type": "command",
            "command": "extension.commandvariable.file.content",
            "args": {
                "fileName": "${workspaceFolder}/.vscode/ConfigData",
                "key": "KEY1",
                "default": ""
            }
        }
    ]
```
The default build task mentioned would be this one from tasks.json
```
{
			"type": "shell",
			"label": "Build Debug Bob",
			"command": "source helpfulScript && cd path && make",

			"options": {
				"cwd": "${workspaceFolder}"
			},
			"problemMatcher": [
				"$msCompile"
			],
			"group": {
				"kind": "build",
				"isDefault": true
			}
		}
```

I've tried a few things, and I have found a combination on windows that does work - but it doesn't work on linux, I suppose because of the different shells handling stuff differently?

if I change ConfigData to have
```
KEY0=c:/path/to/thing
KEY1=["--arg1", "--arg2", "--arg3"]
```
and launch.json not to have the square brackets around the use of GetARG
```
...
"args": "${input:GetARG}",
...
```
I was hoping not to have to change the format in ConfigData, but I will if I have to!  I was also hoping to find a solution that would work on linux too (where I'm using "CodeLLDB" extension by "Vadim Chugunov" rather than Microsoft's C/C++ one for debugging).

Having written all that, I can see why you might say "just change the format in ConfigData, and no you won't find a solution that works on both platforms because you're changing so many things at once"!  But thank you for your time all the same

**Comment by rioj7** [comment]
@bpayne312  What you try to do is execute a command with arguments in different shells on the same or different OS.
It is unacceptable that VSC behaves different in these cases for parsing `args` property and passing them to the JavaScript `process`(??) call.

We want uniform handling of different amount of arguments in each shell. It probably works if you set `args` to an array of strings with the individual arguments. But sometimes you want to pass more or less arguments depending on the choice of a QuickPick. I'm not constructing 11 launch configs with 0 .. 10 argument strings in the array that each fetch a particular argument. And you have to get a way to select a particular launch config based on the QuickPick item selected. It would also mean you need 10 `transform` `inputs`. If the tool inside can split the string with all the arguments or just construct a full command string to pass to a JavaScript `process` variant and let the shell parse the command line and handling the quoting or arguments with spaces,....

I think this asks for a VSC issue to get this fixed in an upcoming release. Most likely the environment set/restore could hinder this. So we only do set the environment and not try to restore. Just kill the terminal if you have a problem with environment variables from a previous run.

**Comment by bpayne312** [comment]
Yeah it's definitely annoying that VSC makes it this difficult - I frequently provide different numbers of arguments, so many different configs for each wouldn't be suitable.

Thank you very much for your responses and advice, it's good to know I haven't been missing an obvious solution to my problem.
