### ISSUE TITLE
file.content `fileName` arg does not support `${input:..}` variables

### ISSUE THREAD

**Issue by bentheadset** [rioj7/command-variable#21]
`${input:...}` is not expanded within the `extension.commandvariable.file.content` arg `fileName`

```
intputs: [
    {
      "type": "pickString",
      "id": "appName",
      "description": "What APP are you running? (eg 'APP=... make test')",
      "options": [
        "app1",
        "app2",
      ],
      "default": "app1"
    },
    {
      "type": "command",
      "id": "myid",
      "command": "extension.commandvariable.file.content",
      "args": {
        "fileName": "${workspaceFolder}/app1.txt", // WORKS as expected
        // "fileName": "${workspaceFolder}/${input:appName}.txt", // NOT working; evaluates to 'ValueNotSet' irrespective of choice
        "key": "PYTHONPATH_prod",
        "default": "ValueNotSet"
      }
    }
]
```

**Comment by rioj7** [comment]
@bentheadset  The problem is how to determine which `task.json` or `launch.json` the command is called from. In case of Multi Root it is even more difficult.

This problem can be solved by adding arguments where it is specified which workspace by name (if Multi Root) is used and if it is the launch or task file if both are in `.vscode`

Another option is to specify all the properties of the pickString in the `${input}` variable by separating them with special string (user chosen). This can result in a very big variable description.

For the user it is simplest to specify workspace and file.

And I have to implement all the logic of the  because I can't ask VSC to evaluate a particular `${input}`.

I already have `extension.commandvariable.pickStringRemember` implemented, it can the same as `pickString` and also support `[label,value]` options. If we add an args property `pickStringRemember` with value an object with keys the name of the input and the value are the arguments of `pickStringRemember`. Easy to implement and not likely the user wants to reuse a particular input, otherwise he has to copy/paste the property

```
    {
      "type": "command",
      "id": "myid",
      "command": "extension.commandvariable.file.content",
      "args": {
        "fileName": "${workspaceFolder}/${pickStringRemember:appName}.txt",
        "key": "PYTHONPATH_prod",
        "default": "ValueNotSet",
        "pickStringRemember": {
            "appName": {
                "description": "What APP are you running? (eg 'APP=... make test')",
                "options": [
                    "app1",
                    "app2",
                ],
                "default": "app1"
            }
        }
      }
    }
```

**Comment by rioj7** [comment]
@bentheadset Try v1.20.0

**Comment by rioj7** [comment]
@renyhp Please create a new issue (with the same text as comment) (to keep record of who proposed) and reference this issue if needed
