### ISSUE TITLE
why removeWorkspacePath didn't work

### ISSUE THREAD

**Issue by cadem** [rioj7/command-variable#66]
I have the following setting, but workspacepath didn't be removed from file pick list. How do I config this property?

```json
{
            "id": "fileTestPick",
            "type": "command",
            "command": "extension.commandvariable.file.pickFile",
            "args": {
              "fromFolder": {
                "predefined": [
                  {
                    "path":"${workspaceFolder}/tests/system-test/mytest",
                    "label":"mytest"
                  }
                ],
                "labelTransform": ["useLabel","removeWorkspacePath"]
              },             
            }
```

**Comment by cadem** [comment]
setting is .vscode/setting.json? I already add [commandvariable.file.pickFile.labelMaximumLength] in it, but it display in gray, it doesn't seem to work at all.

**Comment by rioj7** [comment]
@cadem Because it is scope dependent, you can only set it in the Global/User settings. It depends on YOUR machine not your project. Don't bother other team members with your machine settings.

If you use the settings GUI you will not find the setting in the Workspace and Folder tab.

**Comment by cadem** [comment]
I set it in my settings, but it still doesn't work.

**Comment by rioj7** [comment]
@cadem I have recreated your folders setup.

`labelTransform` is part of the `fromFolder` property. And only applies to the **Folder Pick** list.

If you have `"useLabel"` as part of the `"labelTransform"` the shown label is almost never bigger than the `commandvariable.file.pickFile.labelMaximumLength` setting. You set `"label":"mytest"`, so that string will be used for that folder entry in the Folder Pick list.

I used `"labelTransform": ["removeWorkspacePath"]`

What I observe is that the string `${workspaceFolder}` is not removed from the label. Maybe I need to fix that. Reason I had never tested the code with a variable in the path and the variable substitution is done **after** the Folder Pick.

If I select that folder it shows me the full path of the files in the **File Pick** list. Because `display` default value is `fullPath`. If you set `display` to `fileName` it shows the file name in the label and the folder path in the detail.

Maybe you want to see the full relative path. I can add an option to `display` with the value `relativePath`. In the File Pick you would see label entries like:

* `tests/system-test/mytest/file-001.txt`
* `tests/system-test/mytest/file-002.txt`
* `tests/system-test/mytest/more-tests/file-101.txt`
* `tests/system-test/mytest/more-tests/file-102.txt`

Please specify what you see and what you expect to see.

**Comment by cadem** [comment]
I see the full path, and I want to see relative path, because I have workspace with long path, when I use file pick, I only can see workspace path in the list. And I don't think filename option is useful, because file is order by filename, not grouped by the folder which the file is put in, it is difficult to find a file without folder group, specially with many folder and many files in it.

**Comment by cadem** [comment]
Futhermore, if I set ${workspaceFolder}/tests/system-test/mytest, and set relative path option, you remove all of it, only showing files under mytest is good too.

**Comment by rioj7** [comment]
@cadem 

>and set relative path option, you remove all of it, only showing files under mytest is good too

sounds like you tried `"display": "relativePath"`?? It is not implemented.

* `workspaceRelativePath` : show file path relative to the workspace
* `folderRelativePath` : show file path relative to the used folder, use last part of folder path too, here `mytest`

By adjusting the label you still have fuzzy search over the relative path.

**Comment by rioj7** [comment]
@cadem Try v1.54.0

The `display` option name added is `relativePath` and it the default now.

You don't have `display` so it should now work as you expected.

**Comment by cadem** [comment]
Both removeWorkspacePath and relativePath works, very nice. Thanks.

**Comment by rioj7** [comment]
@cadem it is not due to `removeWorkspacePath` that the WS folder part is removed from the File Pick list, it is part of the `relativePath` option and the WS path is replaced by `${ws:name}`
