### ISSUE TITLE
Error message not helpful when file does not exist

### ISSUE THREAD

**Issue by vgeza-cenos** [rioj7/command-variable#72]
Hi,
The problem is that it is not obvious that the file does not exist, since the message says **"Unexpected token 'U', 'Unknown' is not valid JSON"**. Am I using it wrong?
Here is the part of inputs array in my launch.json
```    
{        
        "id": "some_path",
        "type": "command",
        "command": "extension.commandvariable.file.content",
        "args": {
              "fileName": "${workspaceFolder}/.vscode/path_config.json",
              "json": "content.THIRD_PARTY_PATH",
              "default": ""
        }
}
```
Thanks!

**Comment by rioj7** [comment]
@vgeza-cenos What do you expect, the command is used and should return a string, the file is not there so the content is `Unknown`, the same for any key-value, JSON, YAML expression.

And also when the file exists and key-value, JSON, YAML expression is not found you get `Unknown`.

Do you expect the default value to show?

Returning an empty string will in most cases crash the program using the command because an argument is missing a value.

**Comment by vgeza-cenos** [comment]
@rioj7 If file does not exist, I would expect an error message saying that file is not found. I was attempting to read multiple variables from different files, and the message did not provide much assistance. It failed to identify the specific variable at which the error occurred or provide details about the nature of the error itself.

**Comment by rioj7** [comment]
@vgeza-cenos if you define the `args` property `"debug":true` a call to `extension.commandvariable.file.content` will show a number of log messages in the **Developer Tools Console** of VSC (**Help** > **Toggle Developer Tools**)

messages regarding file exist are
```none
readFileContent: test if file exists: file_path
readFileContent: read file before utf8 conversion
```
if you see both messages the file is found

What is missing are log messages regarding the key or expression to search. I will add them.

**Comment by rioj7** [comment]
@vgeza-cenos You can try v1.55.1
