### ISSUE TITLE
how to read resolved `python.defaultInterpreterPath` string as task command from `settings.json`?

### ISSUE THREAD

**Issue by zhuoqun-chen** [rioj7/command-variable#87]
Hi @rioj7 ! Thank you for making this amazing extension!

I have a `settings.json` under a workspace called `dummy_ws`

```json
{
    "python.defaultInterpreterPath": "${env:HOME}/miniconda3/my_venv",
}
```

what I tried:

```jsonc
"tasks": [
    {
            "label": "python args",
            // "command": "${command:python.interpreterPath}", // won't work
            "command": "${input:venvPythonExecutable}",
            "args": [
                "${file}"
            ],
            "options": {
                "cwd": "${workspaceFolder}",
            }
    }
"inputs": [
    {
            "id": "venvPythonExecutable",
            "type": "command",
            "command": "extension.commandvariable.file.content",
            "args": {
                "fileName": "${workspaceFolder}/.vscode/settings.json",
                "json": "content.python.defaultInterpreterPath",
            }
    }
]
```

But shows error: `Expected double-quoted property name in JSON at position 77`

I also tried

```json
"id": "venvPythonExecutable",
"type": "command",
"command": "extension.commandvariable.config.expression",
"args": {
    "configVariable": "python.defaultInterpreterPath",
    "expression": "content",
}
```

but it will only resolve to raw string "python", this is not what I want, I actually needs to be resolved to sth like:

`/home/<username>/miniconda3/my_venv`

Could you please give me some help here?

**Comment by rioj7** [comment]
@zhuoqun-chen 

I don't know anaconda, but I don't think that `${env:HOME}/miniconda3/my_venv` is an executable.

I use python module `venv` virt envs.

I reproduced the case you suggest and get a different result.

I used a file named: `.vscode/settings-test.json`

With content:

```json
{
  "pppyyy.defaultInterpreterPath": "${env:HOME}/.venv-test/Scripts/python.exe"
}
```

Because `.` is part of the key and it is also the Javascript member operator and I interpret the `json` property as a Javascript expression you have to use the alternative member syntax: `"json": "content['python.defaultInterpreterPath']"`

Task `input` is:

```json
    {
      "id": "venvPythonExecutable",
      "type": "command",
      "command": "extension.commandvariable.file.content",
      "args": {
          "fileName": "${workspaceFolder}/.vscode/settings-test.json",
          "json": "content['pppyyy.defaultInterpreterPath']",
      }
    }
```

I get as result: `${env:HOME}/.venv-test/Scripts/python.exe`.

It turns out that the file content value does not have variable substitution.

I can add a property that signals to perform variable substitution on the command result. This can be done before or after storing the value in the remember store, and then I have to add this to the `remember` command too.

----

Where in the JSON file is position 77?

**Comment by zhuoqun-chen** [comment]
Hey @rioj7 , thank you for taking time investigating my use case and I appreciate that!

There are 3 things here:

1. You can just ignore the `Expected double-quoted property name in JSON at position 77` error,  what you mentioned in your response: `"json": "content['pppyyy.defaultInterpreterPath']"` is exactly what I'm looking for.

2. I'm gonna love the feature to have the var substitution for sth like: `"${env:HOME}/.venv-test/Scripts/python.exe"`, this is gonna make this extension even more powerful 😀.

3. My original commented command: `"command": "${command:python.interpreterPath}"` now works as expected so the use case above can be used as a back-up plan for me (which is gonna happen once you add that substitution feature).

Thank you again for making this extension! ❤️❤️❤️
