### ISSUE TITLE
pickStringRemember does not display remembered value in prompt

### ISSUE THREAD

**Issue by gavinltomra** [rioj7/command-variable#98]
Using an input like this:

```
        {
            "id": "types",
            "type": "command",
            "command": "extension.commandvariable.pickStringRemember",
            "args": {
                "description": "Select the type of build",
                "key": "build_types",
                "rememberTransformed": true,
                "options": [
                    ["Last used", "${remember:build_types}"],
                    ["All", ""],
                    ["Debug", "-cDebug"],
                    ["Release", "-cRelease"],
                ]
            }
        },
```

When displaying the pick list, VSC displays the literal text `${remember:build_types}` next to "Last used", regardless of whether the value has been remembered or not.  It would be nicer if it expanded this to the remembered value whenever possible.

It does otherwise work as expected, though (i.e. selecting "Last used" will actually substitute the remembered value when running the task, and selecting one of the other options will update the remembered value as expected).

**Comment by rioj7** [comment]
@gavinltomra The `value` property variables are only resolved **after** selecting the option. Because it can contain some kind of UI.

The solution is in one of the many examples.
Search the README for: `Possibilities for the Use previous directory are`

The `[]` syntax for `option` is supported because it was the initial syntax to use, better to use the object-option syntax, you then have full control of what you see. Be sure to use only non-UI variables in `label`, `description`, `detail` properties.

Use:

`{"label": "Last used: ${remember:build_types}", "value":"${remember:build_types}"}`

or:

`{"label": "Last used", "description": "${remember:build_types}", "value":"${remember:build_types}"}`

**Comment by gavinltomra** [comment]
Thanks, the last does what I was expecting.  Apologies for the noise.
